[package]
name = "stellar-soroban"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "stellar_soroban"

[dependencies]
soroban-sdk = "20.3.0"

[profile.release]
opt-level = "s"
strip = true
lto = true
