[profile.default]
src = 'src'
test = 'test'
script = 'script'
libs = ['lib']
solc_version = '0.8.20'
evm_version = 'paris'
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
