[package]
name = "aries"
version = "1.0.0"
authors = []

[addresses]
aries = ""

[dev-addresses]


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

